ALIASDOMAIN = "o365-dev-univention-de"
# ALIASDOMAIN = "u-azure-test-de"
DOMAIN_PATH = "<Replace with your path>"
# DOMAIN = "alphadistrict.onmicrosoft.com"
DOMAIN = "univentiontestgmbh.onmicrosoft.com"
DOMAIN_2 = "office365.dev-univention.de"
OWNER_ID = "d6aab5ff-9c88-4e45-9e0f-1321ee8fc8bd"
