stages:
  - test
  - repo

variables:
  UCS_VERSION: "448"
  UCS_RELEASE: "4.4"
  BRANCH: "4.4"
  SCOPE: "office365"
  LANG: "C.UTF-8"
  DEBIAN_FRONTEND: noninteractive
  CI_REGISTRY: docker-registry.knut.univention.de
  IMAGE_UCSDEV: $CI_REGISTRY/phahn/ucs-devbase:$UCS_VERSION
  IMAGE_UCSLINT: $CI_REGISTRY/ucslint:$UCS_VERSION
  IMAGE_SSH: $CI_REGISTRY/knut/ssh
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_DEPTH: "3"

ucslint:
  stage: test
  image:
    name: $IMAGE_UCSLINT
    entrypoint: [""]
  script:
    - ucslint -j ucslint.xml -x 20
  artifacts:
    reports:
      junit: ucslint.xml

debian:
  stage: test
  interruptible: true
  image: $IMAGE_UCSDEV
  before_script:
    - apt-get -qq --assume-yes build-dep .
  script:
    - dpkg-buildpackage
    - rm -rf deb
    - mkdir deb
    - mv ../*.deb ../*.buildinfo ../*.tar.gz ../*.dsc ../*.changes
  artifacts:
    paths:
      - deb

repo:
  stage: repo
  interruptible: true
  variables:
    GIT_STRATEGY: none
  image:
    name: $IMAGE_SSH
    entrypoint: [""]
  only:
    - $BRANCH
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /skip-build/ || $pipeline =~ /skip-build/"
      when: never
    - if: '$CI_COMMIT_BRANCH == $BRANCH'
      changes:
        - debian/changelog
      when: on_success
  before_script:
    - chmod 0600 "$SSH_PRIVATE_KEY"
  script:
    - echo ssh -o BatchMode=yes -i "$SSH_PRIVATE_KEY" -l build omar.knut.univention.de "repo_admin.py -G $CI_REPOSITORY_URL -p univention-office365 -b $BRANCH -P . -s $SCOPE -r ${UCS_RELEASE}-0-0"

# vim: filetype=yaml expandtab tabstop=2 shiftwidth=2 softtabstop=2
