#!/usr/share/ucs-test/runner python
## -*- coding: utf-8 -*-
## desc: create user in azure, check Data attribute
## tags: [apptest]
## exposure: dangerous
## packages:
##   - univention-office365

import time
import json
import zlib
import base64

import univention.testing.ucr as ucr_test
import univention.testing.udm as udm_test
import univention.testing.utils as utils
from univention.config_registry import handler_set, handler_unset

from helpers.office365_test_helpers import listener_attributes_data, udm_user_args, check_udm2azure_user, setup_logging
from univention.office365.listener import Office365Listener
from univention.office365.azure_auth import AzureAuth, AzureADConnectionHandler


logger = setup_logging()
adconnection_aliases = AzureADConnectionHandler.get_adconnection_aliases()
initialized_adconnections = [adconnection_alias for adconnection_alias in adconnection_aliases if AzureAuth.is_initialized(adconnection_alias)]

print("*** adconnection_aliases={!r}.".format(adconnection_aliases))
print("*** initialized_adconnections={!r}.".format(initialized_adconnections))

with utils.AutomaticListenerRestart():
	with udm_test.UCSTestUDM() as udm:
		with ucr_test.UCSTestConfigRegistry() as ucr:
			ucr.load()
			class _listener(object):
				configRegistry = ucr

			if not initialized_adconnections:
				utils.fail("No configured AD connection, can not start test!")


			for adconnection_alias in initialized_adconnections:
				print("*** Running for adconnection_alias={!r}.".format(adconnection_alias))

				ol = Office365Listener(_listener(), "ucs-test", listener_attributes_data, {}, "dn", adconnection_alias)

				user_args = udm_user_args(ucr, minimal=False)
				user_args["set"]["UniventionOffice365Enabled"] = 1
				user_args["set"]["UniventionOffice365ADConnectionAlias"] = adconnection_alias

				print("*** Creating user with all possible properties...")
				user_dn, username = udm.create_user(check_for_drs_replication=True, **user_args)
				time.sleep(10)

				print("*** Checking that user was created (UniventionOffice365ObjectID in UDM object)...")
				udm_user = ol.udm.get_udm_user(user_dn)
				data = udm_user.get("UniventionOffice365Data")
				data_decoded = Office365Listener.decode_o365data(data)
				
				print("*** Data decoded: %s" % data_decoded)

				objectid_in_azure = data_decoded[adconnection_alias]['objectId']
				print("*** ObjectID in conn %s: %s" % (adconnection_alias, objectid_in_azure))
				if not objectid_in_azure:
					utils.fail("User was not created properly (no UniventionOffice365ObjectID).")

			print("*** All went well for all in {!r}.".format(initialized_adconnections))
