#!/usr/share/ucs-test/runner python
## -*- coding: utf-8 -*-
## desc: change team members in azure
## tags: [apptest]
## exposure: dangerous
## packages:
##   - univention-office365

"""
This test is used to check the team members change in Azure.
- Use o365domain connection
- Create user1, user2, user3 in UDM with UniventionMicrosoft365Team=1
- Create group in UDM with UniventionMicrosoft365Team=1 and UniventionMicrosoft365GroupMembers=[user2_dn, user3_dn] and UniventionMicrosoft365GroupOwners=user_dn
- Check that the team have 3 members (It's using the wait_for_seconds decorator to wait for the team to be created up to 500 seconds)
- Create another 3 users in UDM with UniventionMicrosoft365Team=1 and members of the group
- Check that the team have 6 members
- Remove 2 users from the UDM group
- Check that the team have 4 members
"""
import univention.testing.utils as utils
import univention.testing.ucr as ucr_test
import univention.testing.udm as udm_test
from univention.config_registry import handler_set

import helpers.office365_test_helpers as o365helpers
from univention.office365.microsoft.account import AzureAccount
from univention.office365.microsoft.core import MSGraphApiCore

with utils.AutomaticListenerRestart():
	with udm_test.UCSTestUDM() as udm:
		with ucr_test.UCSTestConfigRegistry() as ucr:
			ucr.load()

			class _listener(object):
				configRegistry = ucr

			alias = 'o365domain'

			core = MSGraphApiCore(AzureAccount(alias))

			handler_set(["office365/groups/sync=yes"])
			utils.restart_listener()

			print("*** Creating members ***")
			user_dn, _ = o365helpers.create_team_member(udm, ucr, alias)
			user2_dn, _ = o365helpers.create_team_member(udm, ucr, alias)
			user3_dn, _ = o365helpers.create_team_member(udm, ucr, alias)

			print("*** Creating Team ***")
			group_dn, group_name = o365helpers.create_team(udm, ucr, owner_dn=user_dn, users=[user2_dn, user3_dn])
			created_team = o365helpers.check_team_created(core, group_name)
			team_id = created_team.id

			team_members = o365helpers.check_team_members(core, team_id, 3)

			print("*** Creating new members ***")
			user_dn, _ = o365helpers.create_team_member(udm, ucr, alias, group_dn)
			user2_dn, _ = o365helpers.create_team_member(udm, ucr, alias, group_dn)
			user3_dn, _ = o365helpers.create_team_member(udm, ucr, alias, group_dn)

			_ = o365helpers.check_team_members(core, team_id, 6)

			udm.remove_object('users/user', dn=user2_dn)
			udm.remove_object('users/user', dn=user3_dn)

			_ = o365helpers.check_team_members(core, team_id, 4)
			print("*** All went well.")