#!/usr/share/ucs-test/runner python3
## -*- coding: utf-8 -*-
## desc: remove externally configured ad connections
## tags: [apptest]
## exposure: dangerous
## packages:
##   - univention-office365

from helpers.office365_test_helpers import setup_logging, remove_externally_configured_adconnections
import univention.testing.utils as utils

logger = setup_logging()

if not remove_externally_configured_adconnections(logger):
	utils.fail("Removing of externally configured ad connections failed!")

print("*** All went well.")
